name: One-time Historical Backfill (Yahoo -> GCS)
on: { workflow_dispatch: {} }

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with: { credentials_json: ${{ secrets.GCP_SA_KEY }} }
      - uses: google-github-actions/setup-gcloud@v2
        with: { project_id: ${{ secrets.GCP_PROJECT_ID }} }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run backfill (Yahoo only)
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE"
          python -m pipeline.backfill_historical
          gsutil ls -r gs://${{ secrets.GCS_BUCKET }}/data/raw || true
