name: BigQuery init (create external table + views)
on: { workflow_dispatch: {} }

jobs:
  bq-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                # pulls your repo (gets bq/init.sql)
      - uses: google-github-actions/auth@v2      # GCP auth via SA key
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Run init.sql with substitutions (safe)
        env:
          PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          DATASET: finnhub_data                 # or put in secrets
          BUCKET:  ${{ secrets.GCS_BUCKET }}
        run: |
          # 1) Render placeholders into a temp file
          sed -e "s/@project_id/$PROJECT/g" \
              -e "s/@dataset/$DATASET/g" \
              -e "s/@bucket/$BUCKET/g" \
              bq/init.sql > /tmp/init.sql

          # 2) (optional) show first part for debugging
          sed -n '1,60p' /tmp/init.sql

          # 3) Run the SQL by piping the file to bq (avoids CLI flag parsing)
          bq query --use_legacy_sql=false --quiet < /tmp/init.sql

