name: BigQuery init (create external table + views)
on: { workflow_dispatch: {} }

jobs:
  bq-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                # pulls your repo (gets bq/init.sql)
      - uses: google-github-actions/auth@v2      # GCP auth via SA key
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Run init.sql with substitutions
        env:
          PROJECT: ${{ secrets.GCP_PROJECT_ID }}           # e.g. finnhubmacostrategy
          DATASET: finnhub_data                       # or put in secrets
          BUCKET: ${{ secrets.GCS_BUCKET }}                # e.g. finnhub-mac-data-130701
        run: |
          # Replace @placeholders and run against BigQuery
          bq query --use_legacy_sql=false "$(
            sed -e "s/@project_id/$PROJECT/g" \
                -e "s/@dataset/$DATASET/g" \
                -e "s/@bucket/$BUCKET/g" bq/init.sql
          )"
