name: Deploy Data Pipeline (Function + Scheduler)

on:
  push: { branches: [ "main" ] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Authenticate with your GCP Service Account key (JSON in repo secrets)
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud and set the default project (no auth fields here)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 👉 Deploy ONLY the daily updater function (no Cloud Run / containers now)
      #    This function:
      #      - appends new daily bars from Finnhub to CSVs in GCS
      #      - computes MACO in Python and writes signals to BigQuery
      - name: Deploy Cloud Function (daily updater + MACO publish)
        run: |
          gcloud functions deploy finnhub-daily-updater \
            --gen2 \
            --region ${{ secrets.GCP_REGION }} \
            --runtime python311 \
            --source . \
            --entry-point run_update \
            --trigger-http --allow-unauthenticated \
            --service-account ${{ secrets.FN_SA_EMAIL }} \
            --set-env-vars GCS_BUCKET=${{ secrets.GCS_BUCKET }},DATA_PREFIX=data/raw \
            --set-env-vars BQ_PROJECT=${{ secrets.GCP_PROJECT_ID }},BQ_DATASET=finnhub_data,BQ_TABLE=maco_signals \
            --set-secrets FINNHUB_API_KEY=${{ secrets.FINNHUB_SECRET_NAME }}:latest

      # Schedule the function daily at 01:00 UTC (adjust as you like)
      - name: Ensure Scheduler job (calls the function daily)
        shell: bash
        run: |
          FN_URL=$(gcloud functions describe finnhub-daily-updater \
            --region=${{ secrets.GCP_REGION }} \
            --format="value(serviceConfig.uri)")

          LOCATION=${{ secrets.GCP_REGION }}
          JOB=finnhub-maco-daily

          if gcloud scheduler jobs describe "$JOB" --location="$LOCATION" >/dev/null 2>&1; then
            gcloud scheduler jobs update http "$JOB" \
              --location="$LOCATION" \
              --schedule="0 1 * * *" \
              --time-zone="UTC" \
              --uri="$FN_URL" \
              --http-method=GET \
              --oidc-service-account-email=${{ secrets.FN_SA_EMAIL }}
          else
            gcloud scheduler jobs create http "$JOB" \
              --location="$LOCATION" \
              --schedule="0 1 * * *" \
              --time-zone="UTC" \
              --uri="$FN_URL" \
              --http-method=GET \
              --oidc-service-account-email=${{ secrets.FN_SA_EMAIL }}
          fi

      - name: Show Function URL
        run: |
          gcloud functions describe finnhub-daily-updater \
            --region=${{ secrets.GCP_REGION }} \
            --format="value(serviceConfig.uri)"
