name: Build & Deploy to Google Cloud
on:
  push: { branches: [ "main" ] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ AUTHENTICATE to GCP using the SA key JSON stored in GCP_SA_KEY
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # SA key JSON

      # ✅ INSTALL gcloud & set project (no auth fields here)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build the container (points to your Dockerfile path)
      - name: Build image
        run: |
          # Cloud Build will auto-pick ./Dockerfile at repo root
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/finnhub-mac-app .

      # Deploy Streamlit to Cloud Run
      - name: Deploy Cloud Run (Streamlit app)
        run: |
          gcloud run deploy finnhub-mac-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/finnhub-mac-app \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars GCS_BUCKET=${{ secrets.GCS_BUCKET }} \
            --set-secrets FINNHUB_API_KEY=${{ secrets.FINNHUB_SECRET_NAME }}:latest \
            --min-instances=0 --max-instances=3 --concurrency=10 --memory=1Gi --cpu=1 --timeout=900

      # Deploy Cloud Function (deploy from repo root so pipeline/ is included)
      - name: Deploy Cloud Function (daily updater)
        run: |
          gcloud functions deploy finnhub-daily-updater \
            --gen2 --region=${{ secrets.GCP_REGION }} --runtime=python311 \
            --source=. \
            --entry-point=run_update \
            --trigger-http --allow-unauthenticated \
            --set-env-vars GCS_BUCKET=${{ secrets.GCS_BUCKET }} \
            --set-secrets FINNHUB_API_KEY=${{ secrets.FINNHUB_SECRET_NAME }}:latest

      # Create/Update Scheduler job to call the function daily 01:00 UTC
      - name: Ensure Scheduler job
        shell: bash
        run: |
          FN_URL=$(gcloud functions describe finnhub-daily-updater --region=${{ secrets.GCP_REGION }} --format="value(serviceConfig.uri)")
          if gcloud scheduler jobs describe finnhub-daily >/dev/null 2>&1; then
            gcloud scheduler jobs update http finnhub-daily \
              --schedule="0 1 * * *" --time-zone="UTC" \
              --uri="$FN_URL" --http-method=GET
          else
            gcloud scheduler jobs create http finnhub-daily \
              --schedule="0 1 * * *" --time-zone="UTC" \
              --uri="$FN_URL" --http-method=GET
          fi

      # Print app URL
      - name: Show Cloud Run URL
        run: gcloud run services describe finnhub-mac-app --region=${{ secrets.GCP_REGION }} --format="value(status.url)"