name: Seed Historical Data
on: { workflow_dispatch: {} }

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ Auth then setup gcloud (same pattern)
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run seed
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}   # where CSVs go
        run: |
          # Make 'pipeline' imports work
          export PYTHONPATH="$GITHUB_WORKSPACE"
          # Pull Finnhub key from Secret Manager
          export FINNHUB_API_KEY=$(gcloud secrets versions access latest --secret=${{ secrets.FINNHUB_SECRET_NAME }})
          # Run as a module
          python -m pipeline.fetch_historical
