name: Seed Historical Data
on: { workflow_dispatch: {} }

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ Auth then setup gcloud (same pattern)
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run seed
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}   # where CSVs go
        run: |
           # 1) Ensure imports work
           export PYTHONPATH="$GITHUB_WORKSPACE"

           # 2) Fetch key Directly
           export FINNHUB_API_KEY='${{ secrets.FINNHUB_DIRECT_KEY }}'

           # 3) Sanity: print key length only (masked), fail if empty
           echo "Key length: ${#FINNHUB_API_KEY}"
           test ${#FINNHUB_API_KEY} -gt 20 || { echo "Key missing/too short"; exit 1; }

           # 4) API smoke test (should be JSON with price fields)
           RESP=$(curl -s "https://finnhub.io/api/v1/quote?symbol=AAPL&token=${FINNHUB_API_KEY}")
           echo "$RESP" | grep -qi '"error"' && { echo "Finnhub auth failed"; exit 1; }

           # 5) Run the seeder as a module
           python -m pipeline.fetch_historical
